In [1]:
import pandas as pd

Создайте фрейм данных views с двумя столбцами: datetime и user, прочитав feed-views.log.
- Конвертировать datetimeв datetime64[ns] Dtype.
- Извлечь год, месяц, день, час, минуту и ​​секунду из значений столбца datetimeв новые столбцы.

In [6]:
views = pd.read_csv('../data/feed-views.log', sep ='\t', names = ['datetime', 'user'])

In [8]:
views['datetime'] = pd.to_datetime(views['datetime'])

In [10]:
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views["day"] = views["datetime"].dt.day
views["hour"] = views["datetime"].dt.hour
views["minute"] = views["datetime"].dt.minute
views["second"] = views["datetime"].dt.second

Создайте новый столбец daytime.


- Присвойте значение времени суток, если час попадает в определённый интервал. Например, присвойте значение «после полудня», если час больше 11, но меньше или равен 17.

- 0–3:59 = ночь, 4–6:59 = раннее утро, 7–10:59 = утро, 11–16:59 = день, 17–19:59 = ранний вечер, 20–23:59 = вечер

- Используйте метод cut для решения этой подзадачи.

- Назначьте столбец user в качестве индекса.

In [17]:
bins = [0, 4, 7, 11, 17, 20, 24]
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

In [18]:
views['daytime'] = pd.cut(views['hour'], bins = bins, labels = labels, right=False)

In [21]:
views = views.set_index("user")

Рассчитайте количество элементов в вашем фрейме данных.
- Используйте метод count().
- Рассчитайте количество элементов в каждой категории времени суток, используя данный value_counts() метод.

In [23]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [24]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

Сортируйте значения в таблице данных по часам, минутам и секундам в порядке возрастания одновременно, а не по одному.

In [25]:
views = views.sort_values(by = ['hour', 'minute', 'second'])

In [26]:
views.head()

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night

Рассчитайте минимум и максимум для часов, а также режим для дневных категорий.
- Рассчитайте максимальный час для строк, где время суток — ночь.
- Рассчитайте минимальный час для строк, где время суток — утро.
- Кроме того, выясните, кто посещал страницу в эти часы, и приведите один пример.
- Рассчитайте моду для часа и времени суток.

In [28]:
night_max  = views.loc[views["daytime"] == "night", "hour"].max()
night_max

3

In [32]:
morning_min = views.loc[views['daytime'] == 'morning', 'hour'].min()
morning_min

8

In [39]:
morning_example = views.loc[views["hour"] == morning_min]
morning_example.iloc[0]

datetime    2020-05-15 08:16:03.918402
year                              2020
month                                5
day                                 15
hour                                 8
minute                              16
second                               3
daytime                        morning
Name: alexander, dtype: object

In [41]:
views["hour"].mode()[0]

22

In [42]:
views["daytime"].mode()[0]

'evening'

Показывать три самых ранних и три самых поздних часа дня и соответствующие им имена пользователей с помощью nsmallest() и nlargest().

In [48]:
views.nsmallest(3, "hour")["hour"]

user
valentina    0
valentina    0
pavel        0
Name: hour, dtype: int32

In [47]:
views.nlargest(3, 'hour')['hour']

user
ekaterina    23
ekaterina    23
ekaterina    23
Name: hour, dtype: int32

Используйте describe()метод для получения основных статистических данных по столбцам.
- Чтобы найти наиболее популярный интервал посещений, рассчитайте межквартильный размах для часа, извлекая значения из результата метода describe() и сохраняя их в переменной iqr.

In [49]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1076,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000
mean,2020-05-10 09:00:41.211420672,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:49.857472,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:44:34.749530624,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000
max,2020-05-22 10:36:14.662600,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.335557,4.906567,6.955490,17.689388,17.405506

In [53]:
desc = views['hour'].describe()
iqr = desc['75%'] - desc['25%']
iqr

9.0