In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('../data/feed-views.log', sep = '\t', skiprows = [2,3], skipfooter=2, engine = 'python', names = ['datetime', 'user'], index_col="datetime")

In [5]:
data.index.name = "date_time"

In [6]:
data.to_csv("feed-views-semicolon.log", sep=";")

In [7]:
data.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [8]:
data.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel